### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by JDFagan** [leinardi/mypy-pycharm#22]
### Step 1: Are you in the right place?
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of the plugin.

### Step 2: Describe your environment
 - Plugin version: `0.10.2`
 - PyCharm/IDEA version: `2018.2.4`
 - Mypy version: `0.630`

### Step 3: Describe the problem:
Received following Java error message when starting up PyCharm after restarting after installing this plugin via PyCharm's repository..

#### Steps to reproduce:

  1. Installed mypy into my Miniconda environment via ```conda install mypy```
  2. Installed mypy-pycharm via PyCharm's plugin repository
  3. Restarted PyCharm which then opened up my prior opened PyCharm projects.

#### Observed Results:

  * Popup message with following Java stack trace:

```
java.lang.Throwable: Error while checking Mypy path: Traceback (most recent call last):
  File "/Users/JDFagan/miniconda3/bin/mypy", line 7, in <module>
    from mypy.__main__ import console_entry
ModuleNotFoundError: No module named 'mypy'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.leinardi.pycharm.mypy.mpapi.MypyRunner.isMypyPathValid(MypyRunner.java:102)
	at com.leinardi.pycharm.mypy.mpapi.MypyRunner.checkMypyAvailable(MypyRunner.java:176)
	at com.leinardi.pycharm.mypy.mpapi.MypyRunner.checkMypyAvailable(MypyRunner.java:152)
	at com.leinardi.pycharm.mypy.MypyInspection.inspectFile(MypyInspection.java:76)
	at com.leinardi.pycharm.mypy.MypyInspection.lambda$checkFile$0(MypyInspection.java:65)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:337)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
  

#### Expected Results:

  * No stacktrace

#### Relevant Code:

Not sure yet if it's caused by specific code in my project.

N/A

Forgot to snap screenshot.  Will update this issue if I can reproduce it.

**Comment by JDFagan** [comment]
Note, I restarted again and the problem is no longer there - I think this issue can be closed.
