### ISSUE TITLE
Traceback when opening PyCharm project

### ISSUE THREAD

**Issue by tim-mitchell** [leinardi/mypy-pycharm#23]
### Step 2: Describe your environment
 - Plugin version: `0.10.2`
 - PyCharm/IDEA version: `2018.2.4`
 - Mypy version: `None`

#### Steps to reproduce:

  1. Install mypy plugin without mypy package
  2. Open another project

  * IDE Fatal Error notification.
  

#### Expected Results:

  * mypy plugin disabled

#### Relevant Code:

```java
System.out.println("Hello, world!");
```

```Gradle
java.lang.Throwable: Error while detecting Mypy path: INFO: Could not find files for the given pattern(s).
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.leinardi.pycharm.mypy.mpapi.MypyRunner.detectSystemMypyPath(MypyRunner.java:212)
	at com.leinardi.pycharm.mypy.mpapi.MypyRunner.getMypyPath(MypyRunner.java:146)
	at com.leinardi.pycharm.mypy.mpapi.MypyRunner.getMypyPath(MypyRunner.java:124)
	at com.leinardi.pycharm.mypy.mpapi.MypyRunner.checkMypyAvailable(MypyRunner.java:176)
	at com.leinardi.pycharm.mypy.mpapi.MypyRunner.checkMypyAvailable(MypyRunner.java:152)
	at com.leinardi.pycharm.mypy.MypyInspection.inspectFile(MypyInspection.java:76)
	at com.leinardi.pycharm.mypy.MypyInspection.lambda$checkFile$0(MypyInspection.java:65)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:337)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)#### Observed Results:

```

![ide error](https://user-images.githubusercontent.com/9870675/48228531-4e580f80-e40a-11e8-8af4-265b8663fa4c.png)

**Comment by leinardi** [comment]
Hi @tim-mitchell, could you please attach the idea.log file (https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files) after you get the Exception?

**Comment by tim-mitchell** [comment]
[logs-20181112-100519.zip](https://github.com/leinardi/mypy-pycharm/files/2569842/logs-20181112-100519.zip)

**Comment by gantsevdenis** [comment]
same problem
`mypy 0.641`
```
IntelliJ IDEA 2018.2.5 (Ultimate Edition)
Build #IU-182.4892.20, built on October 16, 2018
Licensed to dhatim / Denis Gantsev
You have a perpetual fallback license for this version
Subscription is active until October 1, 2019
JRE: 1.8.0_152-release-1248-b19 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-20-generic
```
Just for info, python is only part of a larger Java project

**Comment by sollyucko** [comment]
Even better would be if it offered to install Mypy if the executable was not found.

**Comment by leinardi** [comment]
@sollyucko that feature was already implemented in version [0.10.0](https://github.com/leinardi/mypy-pycharm/releases/tag/0.10.0)

**Comment by sollyucko** [comment]
I installed it from the plug-in repo just a couple days ago and didn't see a dialog like that.

**Comment by cromat** [comment]
I have the same issue. Seems also that error occurs not only on Pycharm startup, but randomly when Pycharm is running.

Pycharm version: 2018.3.4
Plugin version: 0.10.2
Mypy version: 0.670

**Comment by nilayspshah** [comment]
Facing the same issue. 
I have also linked the mypy executable, as suggested for a similar thread for pylint extension. Pylint is able to run fine post linking the executable, mypy issue persists.

I have installed mypy in a virtual env. 

<img width="1029" alt="Screen Shot 2019-04-18 at 3 09 15 AM" src="https://user-images.githubusercontent.com/3463571/56322774-92082f80-6187-11e9-9c8d-ea963e915a2c.png">

Attaching the relevant idea.log [relevant_idea_log.txt](https://github.com/leinardi/mypy-pycharm/files/3091734/relevant_idea_log.txt)

Seems to be error at [this line of code](https://github.com/leinardi/mypy-pycharm/blob/master/src/main/java/com/leinardi/pycharm/mypy/mpapi/MypyRunner.java#L102)

I am unable to completely understand it but.. Seems like the code is trying to find the __main__ module in the pycharm project path although the mypy is installed in another virtual env directory..

Can you please inspect?
