### ISSUE TITLE
Unable to configure mypy binary on Linux

### ISSUE THREAD

**Issue by MarcinOrlowski** [leinardi/mypy-pycharm#24]
### Step 1: Are you in the right place?
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of the plugin.

### Step 2: Describe your environment
 - Plugin version: 0.10.2
 - PyCharm/IDEA version: 2018.2.4 (CE)
 - Mypy version: 0.641

#### Steps to reproduce:

  1. I am using Ubuntu/Debian based distro
  1. I have both python2 and pythong3 installed
  2. Installed python3-pip
  3. installed mypy using pip3 install mypy
  4. Properly installed in `/usr/local/bin/mypy`
  5. above path is in $PATH
  6. mypy runs when started from command
  7. Attempt to configure your plugin with either `mypy` or `/usr/local/bin/mypy` as mypy binary does not work (test fails) with `Mypy Plugin: Failure: executable "mypy" not found`.

This looks similar to #12

**Comment by flowersw** [comment]
Similar issue here, with pycharm generated stacktrace:
`2018-11-10T13:11:22.487
java.lang.Throwable: Error while checking Mypy path:   File "/home/will/.pyenv/shims/mypy", line 3
    [ -n "$PYENV_DEBUG" ] && set -x
                      ^
SyntaxError: invalid syntax
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.leinardi.pycharm.mypy.mpapi.MypyRunner.isMypyPathValid(MypyRunner.java:102)
	at com.leinardi.pycharm.mypy.mpapi.MypyRunner.checkMypyAvailable(MypyRunner.java:176)
	at com.leinardi.pycharm.mypy.mpapi.MypyRunner.checkMypyAvailable(MypyRunner.java:152)
	at com.leinardi.pycharm.mypy.MypyInspection.inspectFile(MypyInspection.java:76)
	at com.leinardi.pycharm.mypy.MypyInspection.lambda$checkFile$0(MypyInspection.java:65)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:337)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by leinardi** [comment]
@MarcinOrlowski, @flowersw could you please attach the idea.log file (https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files) after you get the Exception?

@MarcinOrlowski which interpreter are you using in PyCharm? The system one or a venv?

**Comment by MarcinOrlowski** [comment]
Here's my stacktrace

```
java.lang.Throwable: Error while checking Mypy path: Traceback (most recent call last):
  File "/usr/local/google/home/orlowskim/mypy", line 7, in <module>
    from mypy.__main__ import console_entry
ImportError: No module named mypy.__main__
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.leinardi.pycharm.mypy.mpapi.MypyRunner.isMypyPathValid(MypyRunner.java:102)
	at com.leinardi.pycharm.mypy.mpapi.MypyRunner.checkMypyAvailable(MypyRunner.java:176)
	at com.leinardi.pycharm.mypy.mpapi.MypyRunner.checkMypyAvailable(MypyRunner.java:152)
	at com.leinardi.pycharm.mypy.MypyInspection.inspectFile(MypyInspection.java:76)
	at com.leinardi.pycharm.mypy.MypyInspection.lambda$checkFile$0(MypyInspection.java:65)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:337)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
I am using 2.7 via venv

**Comment by chadrik** [comment]
I ran into the same problem on MacOS 10.13.  In my case the error is:

```
2019-04-24 23:07:29,098 [ 586314]   INFO - .pycharm.mypy.mpapi.MypyRunner - Command Line string: /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 /usr/local/bin/mypy -V 
```

Why is the plugin using a python interpreter instead of just invoking `mypy` and deferring to the python executable it was installed with?  Trying to guess at another interpreter is just asking for trouble.  In my case it's using python2, which obviously isn't going to work.

**Comment by chadrik** [comment]
It seems like a lot of people are running into this same basic problem.  Issues #18  and #26 are basically the same.

**Comment by paranoidi** [comment]
Yeah, not working on Mint either ... Installed mypy using pipx (so just a virtualenv)

```
$ /home/myusernamehere/.local/pipx/venvs/mypy/bin/mypy
usage: mypy [-h] [-v] [-V] [more options; see below]
            [-m MODULE] [-p PACKAGE] [-c PROGRAM_TEXT] [files ...]
mypy: error: Missing target module, package, files, or command.
```

Direct copy & paste `/home/myusernamehere/.local/pipx/venvs/mypy/bin/mypy` does not work.

**Comment by bandophahita** [comment]
I had similar issue, but in reverse order.  I installed mypy via pip in my virtual environment and pycharm gave the error "executable not found".  I then installed mypy in my actual environment and then the plugin started working in pycharm.

In short, I had to install mypy in both the venv and the regular environment to get the plugin working.

**Comment by sitnarf** [comment]
This managed to fix the issue for me. I belive my pipenv enviroment appears twice in PyCharm. When I select the second one (see screenshot), it even automatically detected the package. 
![image](https://user-images.githubusercontent.com/289991/85158904-160ee900-b25d-11ea-9546-1d85bd2b2159.png)

**Comment by phoenixeliot** [comment]
For some reason I had to do @sitnarf's suggestion as well, and not just set the project interpreter in PyCharm's project settings. This might be because I had to destroy and update my venv recently, and PyCharm didn't seem to fully propagate that through in a few places. This might have just been a fallout from the same not-propagating.

**Comment by aggo** [comment]
in my case, i tried running mypy from the terminal which had the env activated and it wasn't working there either, saying I must install typed-ast for it to work. this is the output:
```
❯❯❯ mypy setup.py
The typed_ast package is not installed.
You can install it with `python3 -m pip install typed-ast`.
❯❯❯ python3 -m pip install typed-ast                                                                                                                                                                                                                ✘ 1 
Collecting typed-ast
  Downloading typed_ast-1.5.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (843 kB)
     |████████████████████████████████| 843 kB 1.5 MB/s            
Installing collected packages: typed-ast
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mypy 0.910 requires typed-ast<1.5.0,>=1.4.0; python_version < "3.8", but you have typed-ast 1.5.1 which is incompatible.
astroid 2.6.2 requires typed-ast<1.5,>=1.4.0; implementation_name == "cpython" and python_version < "3.8", but you have typed-ast 1.5.1 which is incompatible.
Successfully installed typed-ast-1.5.1
❯❯❯ mypy setup.py
mypy: can't read file 'setup.py': No such file or directory```

**Comment by HashimHL** [comment]
Looking into the logfile of pycharm i found out that the plugin is using another pipenv environment that doesnt have mypy instead of using the one pycharm is set on.
```
2022-01-22 17:43:57,883 [ 574664]   INFO - .pycharm.mypy.mpapi.MypyRunner - Command Line string: /home/CCC/.local/share/virtualenvs/XXX-I8024MuH/bin/python /home/XXX/.local/share/virtualenvs/YYY-LWz7hkGd/bin/mypy -V 
```

so i simply deleted the `XXX` environment to force it to use the `YYY` environment and it solved the issue for me.
this [page](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files) helped me find the log file.

**Comment by derula** [comment]
Is there any reason why MyPy has to be installed in the project's virtualenv? Why can't it just be called as a binary, without using the project interpreter?

In my case, using the project interpreter makes no practical sense. I have 10+ projects opened at once (in the same window), each has its own virtualenv and project interpreter.

1. I don't want to install MyPy 10+ times (what for?)
2. I want to run checks across all open projects, not once for each project by changing the project interpreter every time

This reliance on the project interpreter makes this plugin (as well as the PyLint plugin by the same author) effectively useless for me, unfortunately.

**Comment by leinardi** [comment]
If I recall correctly, it was done to be sure that the installation of mypy/pylint has access to the same dependencies of the project, otherwise it may lead to false positive.

If someone wants to try to improve this, PRs are welcome.

**Comment by derula** [comment]
Hmm, that reasoning actually makes sense assuming that `mypy`, like `pylint`, doesn't support separating its own dependencies from the project dependencies. (I know I tried before to convince `pylint` to do that, with extremely limited success.)

In lieu of that, the only other solution I can think of is to improve this plugin's multi-project support, e.g.:

- Automate installing `mypy` into every project's virtualenv
- Run `mypy` for each project in turn and collect results
- Per-project configuration instead of just "for current project"

I know literally nothing about IntelliJ plugin development, but if others are interested in improving multi-project support, I could create a feature request ticket with my UI/UX ideas.
