### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by gijzelaerr** [leinardi/mypy-pycharm#39]
### Step 1: Are you in the right place?
- [x ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ x] I have verified that I am using the latest version of the plugin.

### Step 2: Describe your environment
 - Plugin version: `0.10.4`
 - PyCharm/IDEA version: `2019.2`
 - Mypy version: `0.720`

#### Steps to reproduce:

  1. Run mypy `check project` when our private source code proect is open

#### Observed Results:

Plugins prints:
`The scan failed due to an error - please see the event log for more information`

  

#### Expected Results:

 Get a list of mypy errors.

#### Relevant Code:

Sorry I cant share the project/code.

```2019-08-28
15:24	Unexpected Exception Caught
			The scan failed due to an exception: Error creating Mypy process
			Root cause:
			error=7, Argument list too long
			java.io.IOException: error=7, Argument list too long
			at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
			at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
			at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
			at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
			at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
			at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:443)
			at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:408)
			at com.leinardi.pycharm.mypy.mpapi.MypyRunner.runMypy(MypyRunner.java:304)
			at com.leinardi.pycharm.mypy.mpapi.MypyRunner.scan(MypyRunner.java... (show balloon)

```

![Schermafbeelding 2019-08-28 om 15 31 16](https://user-images.githubusercontent.com/326308/63860172-ec709280-c9a8-11e9-9369-78452f172ac0.png)

**Comment by ohadraz** [comment]
Happens on 0.11.2

**Comment by RunOrVeith** [comment]
Same for me, I renamed the project root folder and then it broke. Even if I deleted the .idea folder it does not work again
